name: Deploy to GitHub Pages

on:
  push:
    branches: 'main'

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'  # Add this to correctly cache dependencies

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci  # Use `npm ci` instead of `npm install` to ensure a clean install

      - name: Build the SvelteKit site
        working-directory: ./frontend
        env:
          BASE_PATH: '/frontend'  # If your app needs this, make sure it's properly used in your SvelteKit config
        run: |
          npm run build
          touch build/.nojekyll  # Add the .nojekyll file to prevent Jekyll processing on GitHub Pages

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: './frontend/build/'


  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1