name: Deploy to GitHub Pages

on:
  push:
    branches: 'main'

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: './frontend/package-lock.json'

      - name: Clean npm cache and remove node_modules
        run: |
          rm -rf ./frontend/node_modules
          rm -f ./frontend/package-lock.json
      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build the SvelteKit site
        working-directory: ./frontend
        env:
          BASE_PATH: './frontend'
        run: |
          npm run build
          touch build/.nojekyll
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: './frontend/build/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1